application: checkasistencia
version: 1
runtime: python27
api_version: 1

threadsafe: false

handlers:
- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico
  
- url: /assets
  static_dir: assets
  
- url: /images
  static_dir: images

- url: .*
  script: main.py

libraries:
- name: django
  version: "1.3"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
